module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      'tiny':{'min':'320px','max':'413px'},
      'xxs':{'min':'375px'},
      'xs':{'min':'414px'},
      's':{'min':'500px'},
      'l':{'min':'600px'},
      'm':{'min':'700px'},
      'md':{'min':'768px'},
      'teta':{'min':'1000px'},
      'ganma':{'min':'1100px'},
      'pcs':{'min':'1300px'},
      'extra':{'min':'1400px'},
    },
    extend: {
      textColor: {
        'primary-black': '#1F1F1F',
        'primary-gray': '#7A7878',
        'primary-yellow': '#FFCD02',
        'primary-blue': '#2a72b7',
      }
      ,borderRadius: {
        '4xl': '3rem',
      },
      borderColor: {
        'primary-blue': '#00AEEF',
        'primary-yellow': '#FFCD02',
      },
      maxWidth: {
        '1/4': '25%',
        '1/2': '50%',
        '7/10': '70%',
        '120rem': '120rem',
      },
      minWidth: {
        '7/10': '70%',
      },
      fontSize: {
        'xxs': ['0.55rem','0.80rem'],
      },
      minHeight: {
        '13rem': '13rem',
        '14rem': '14rem',
        '18rem': '18rem',
        '20rem': '20rem',
        '24rem': '24rem',
        '28rem': '28rem',
        '32rem': '32rem',
        '38rem':'38rem',
        '42rem':'42rem',
        '48rem':'48rem',
        '3/5': '60%',
        '1/5': '20%',
        'inherit':'inherit',
      },
      maxHeight: {
        'unset': 'unset',
        '18rem': '18rem',
        '20rem': '20rem',
        '28rem': '28rem',
        'inherit': 'inherit',
       },
      width: {
        '84':'22rem',
        '104':'28rem',
        '108':'32rem',
        '120':'36rem',
        '9/10':'90%',
        '96%':'96%',
        '92%':'92%',
        '1/20':'5%',
        '1/10':'10%',
        'inherit': 'inherit',
      },
      fontFamily: {
        'kohsantepheat-bold': ['"KohSantepheap-Bold"'],
        'kohsantepheat-light': ['"KohSantepheap-Light"'],
        'kohsantepheat-regular': ['"KohSantepheap-Regular"'],
        'kohsantepheat-thin': ['"KohSantepheap-Thin"'],
        'karma-bold':['"Karma-Bold"'],
        'karma-medium':['"Karma-Medium"'],
        'karma-regular':['"Karma-Regular"'],
        'karma-light':['"Karma-Light"'],
        'karma-semibold':['"Karma-SemiBold"'],
        'display':['"Karma-Bold"'],
        'body':['"Karma-Regular"'],
      },
      height: {
        '100':'27rem',
        '104':'28rem',
        '108':'32rem',
        '110':'33rem',
        '120':'36rem',
        '50%':'50%',
        '96%':'96%',
        '99%':'99%',
        '100%-4px':' calc(100% - 4px)',
        'inherit': 'inherit',
      },
      inset: {
        '1/10':'10%',
        '15%':'15%',
        '40%':'40%',
        '1/6': '20%',
        '5/7':'70%',
        '4/5':'80%',
        '4/6': '33%',
        '96%': '96%',
        '2%': '2%',
        '5%': '5%',
        '4%': '4%',
        'unset':'unset',
      },
      padding: {
        '2%': '2%',
        '4%': '4%'
       },
       margin: {
        '2%': '2%',
        '2px':'2px',
        'inherit':'inherit',
       },
       backgroundImage: {
        'white-r-to-white': 'linear-gradient(271.49deg, rgba(255, 255, 255, 0) -5.21%, rgba(255, 255, 255, 0.494036) 25.98%, #FFFFFF 72.86%)',
       },
    },
  },
  variants: {
    extend: {
      padding:['even','odd'],
      margin:['first'],
      backgroundColor: ['even'],
      display: ['last','hover', 'focus'],
    },
    
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
